### PR TITLE
Updated eslint.js to 2.8.0

### PR DESCRIPTION
**Pull request by rvarbanov**

### CODE REVIEW

**Comment by rvarbanov** [comment]
#176

**Comment by MiguelCastillo** [comment]
What version of ESLint are we upgrading to?

**Comment by rvarbanov** [comment]
2.8.0

**Comment by MiguelCastillo** [comment]
Ok great!  Thanks!

**Comment by MiguelCastillo** [comment]
Did I really ask you that question and the title had the answer?  Man - I must be tired!!  Thanks for your PR :)  Much appreciated.

**Comment by rvarbanov** [comment]
lol, no I just updated the title :)

**Comment by MiguelCastillo** [comment]
Ah!!! :D  sneaky

**Comment by rvarbanov** [comment]
I am just happy I can be of help

**Comment by MiguelCastillo** [comment]
Love it when people help.

**Pull request merged**
