### PR TITLE
Jslint website update

### PR DESCRIPTION
**Pull request by jwestbrook**
Heres a update for the lint errors link that went down

I only updated the JSHint plugin - I'm not sure the JSLint one has a "code" property but it looks like http://linterrors.com/ could be used for that one as well

### CODE REVIEW

**Comment by jwestbrook** [comment]
@MiguelCastillo its a simple change - I'm not going to just merge it without you looking at it.

This should fix #194

**Comment by MiguelCastillo** [comment]
Thank you @jwestbrook .  I am really sorry I didnt see this PR.  If you are interested in maintaining this project, I would happily add you as a contributor. :)

**Comment by jwestbrook** [comment]
@MiguelCastillo you already did - but I wanted a 2nd person to look at it :-)

**Comment by MiguelCastillo** [comment]
ah!  sorry - i remember now :D  my bad.

**Pull request merged**
